### ISSUE TITLE
Transferring repo to `omniauth` org

### ISSUE THREAD

**Issue by jessieay** [aguynamedben/omniauth-atlassian-oauth2#6]
Hi @bobbymcwho - 

I've been in touch with @aguynamedben about transferring this repo to the `omniauth` org on GitHub, similar to what was done for for the OIDC library a while back: https://github.com/omniauth/omniauth_openid_connect/issues/101#issuecomment-1024361295

I am opening this issue to:

1. Make sure you are OK with and expecting this transfer
2. Request that you create a new GitHub team for and add me + @aguynamedben as admins so we can admin the transferred repo (I would also probably add some other GitLab auth team folks but can handle that myself, I think?). I'd like to backfill specs for this library so being an admin will help with that.
3. See if the omniauth group has any other requirements/standards I should be aware of so that I can make sure this library meets those standards.

Thanks! 💟

**Comment by BobbyMcWho** [comment]
Hi @jessieay, happy to help facilitate that, it's pretty straightforward if I recall correctly

**Comment by jessieay** [comment]
Excellent! Let us know how we can help with this or if you have any concerns @aguynamedben. Excited to write those tests!

**Comment by aguynamedben** [comment]
I just transferred the GitHub repo and Rubygems.org entry to @jessieay. +1 for Jessie moving it into the OmniAuth org as necessary!

**Comment by aguynamedben** [comment]
Reopening until y'all actually land it where/how y'all want :D

**Comment by jessieay** [comment]
Ok I've transferred it to OmniAuth so this can be closed now.

Thanks so much @aguynamedben ! 🙏

**Comment by jessieay** [comment]
Ok now that this is transferred: @BobbyMcWho can you create an `omniauth-atlassian-maintainers` team to have the `Admin` role on this repo and add the following users to that team:

* @jessieay 
* @dblessing
* @stanhu 

Thanks so much for all of your help here :)

**Comment by BobbyMcWho** [comment]
@jessieay done
